# Framework for running automated tests on OSB using Travis-CI, see https://github.com/OpenSourceBrain/osb-model-validation

sudo: false  

addons:
  apt:
    packages:
       # Requirements for Brian & NEST
    - python-numpy 
    - python-scipy 
    - python-matplotlib 
    - python-sympy
    
    
language: python
python: 2.7

env:
    - OMV_ENGINE=jNeuroML
    - OMV_ENGINE=jNeuroML_NEURON
    - OMV_ENGINE=jNeuroML_PyNN_NEURON
    - OMV_ENGINE=jNeuroML_validate
    - OMV_ENGINE=NON_OMV_TESTS

install: 
    - pip install git+https://github.com/OpenSourceBrain/osb-model-validation
    # Get latest libNeuroML & pyNeuroML
    - pip install git+https://github.com/NeuralEnsemble/libNeuroML.git@development
    - pip install git+https://github.com/NeuroML/pyNeuroML
    - pip install .

script:
    - omv all -V; export OMV_SUCCESS=$?; echo $OMV_SUCCESS
    - echo "Finished all OMV tests"
    - if [[ ${OMV_ENGINE} == "NON_OMV_TESTS" ]]; then echo "Continuing with tests not under OMV..."; else exit $OMV_SUCCESS; fi
    - echo "Running non OMV tests..."
    - cd examples
    - ./regenerateAll.sh
    - ls -alt
    - cd ../opencortex/test
    - nosetests -vs
    
    
    

