# Framework for running automated tests on OSB using Travis-CI, see https://github.com/OpenSourceBrain/osb-model-validation

sudo: false  

addons:
  apt:
    packages:
    - python-matplotlib 
    - python-tk
    - python-lxml
       # Requirements for Brian & NEST
    - python-numpy 
    - python-scipy 
    - python-sympy
    
language: python
python: 2.7

virtualenv:
    system_site_packages: true
    
env:
    - OMV_ENGINE=jNeuroML
    - OMV_ENGINE=jNeuroML_NEURON
    - OMV_ENGINE=jNeuroML_NetPyNE
    - OMV_ENGINE=jNeuroML_PyNN_NEURON
    - OMV_ENGINE=jNeuroML_validate

install: 
    - pip install git+https://github.com/OpenSourceBrain/osb-model-validation

script:
    - omv all -V
    - omv list-engines
    
    
    

