# Framework for running automated tests on OSB using Travis-CI, see https://github.com/OpenSourceBrain/osb-model-validation

dist: xenial
sudo: false  

addons:
  apt:
    packages:
    - python-matplotlib 
    - python-tk
    - python-lxml
       # Requirements for Brian & NEST
    - python-numpy 
    - python-scipy 
    - python-sympy
    - python-tables 
    - python-tornado

    
language: python

python:
  - 2.7
  - 3.6
  
virtualenv:
    system_site_packages: true

    
env:
    - OMV_ENGINE=jNeuroML
    #- OMV_ENGINE=jNeuroML_NEURON
    - OMV_ENGINE=jNeuroML_NetPyNE
    #- OMV_ENGINE=jNeuroML_PyNN_NEURON
    #- OMV_ENGINE=jNeuroML_validate
    - OMV_ENGINE=NON_OMV_TESTS

install: 
    - git clone https://github.com/OpenSourceBrain/osb-model-validation
    - cd osb-model-validation
    - git checkout test_nrn76 
    - python setup.py install
    - cd ..
    
    - pip install matplotlib --upgrade # This is because Matplotlib v2.x is required for NetPyNE...
    
    - pip install .

script:
    - omv all -V; export OMV_SUCCESS=$?; echo $OMV_SUCCESS
    - echo "Finished all OMV tests"
    - omv list-engines -V
    - if [[ ${OMV_ENGINE} == "NON_OMV_TESTS" ]]; then echo "Continuing with tests not under OMV..."; else exit $OMV_SUCCESS; fi
    - echo "Running non OMV tests..."
    - cd examples
    - ./regenerateAll.sh
    - ls -alt
    - cd ../opencortex/test
    - nosetests -vs
    
    
    

